This famous (Fisher's or Anderson's) iris data set gives the measurements in centimeters of the variables sepal length and width and petal length and width, respectively, for 50 flowers from each of 3 species of iris. The species are Iris setosa, versicolor, and virginica.

Clustering - K-means
========================================================

Preparação dos Dados
-------------------

```{r}
# Dados originais
str(iris)
# Preparação dos dados para o K-means (apenas variáveis quantitativas)
newiris <- iris
newiris$Species <- NULL
str(newiris)
```

Execução do algoritmo de agrupamento
------------------------------------

```{r}
# Execução do agrupamento k-means
kmObject <- kmeans(newiris, 3)
kmObject
#Comparando o agrupamento com os dados originais
table(iris$Species, kmObject$cluster)
```

Visualização do agrupamento
---------------------------
```{r}
plot(newiris$Sepal.Length, newiris$Sepal.Width, col=kmObject$cluster, main="K-means Clustering of Iris Data Set (50 flowers)", xlab="Sepal Length (cm)", ylab="Sepal Width (cm)")
points(kmObject$centers[, c("Sepal.Length", "Sepal.Width")], col=unique(iris$Species), pch=16, cex=2)
legend("bottomright", levels(iris$Species), pch=1, col=unique(iris$Species))
```
```{r}
plot(newiris$Petal.Length, newiris$Petal.Width, col=kmObject$cluster, main="K-means Clustering of Iris Data Set (50 flowers)", xlab="Petal Length (cm)", ylab="Petal Width (cm)")
points(kmObject$centers[, c("Petal.Length", "Petal.Width")], col=unique(iris$Species), pch=16, cex=2)
legend("bottomright", levels(iris$Species), pch=1, col=unique(iris$Species))
```
